// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATe6vbgujXfaLLe21Qa5_P7kjLE-2V5Yo',
    appId: '1:897526227176:web:7b8cc1a15524481f7de95d',
    messagingSenderId: '897526227176',
    projectId: 'store-app-acd53',
    authDomain: 'store-app-acd53.firebaseapp.com',
    storageBucket: 'store-app-acd53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH0J72gnm_PYPlR1eAp9tkqo7WFUVN-NM',
    appId: '1:897526227176:android:0d1f7afe7241d2447de95d',
    messagingSenderId: '897526227176',
    projectId: 'store-app-acd53',
    storageBucket: 'store-app-acd53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcmooprLpn_vroiyhpmHebzkz-3tE0zDg',
    appId: '1:897526227176:ios:d5fce96209141fc47de95d',
    messagingSenderId: '897526227176',
    projectId: 'store-app-acd53',
    storageBucket: 'store-app-acd53.appspot.com',
    iosBundleId: 'com.example.flutterTask4',
  );
}
